name: exness-poler

services:

  redis:
    image: redis:latest
    container_name: exness-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: exness-timescaledb
    environment:
      POSTGRES_DB: exness-timescaledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # restart: unless-stopped

volumes:
  exness:
